package mnix.mobilecloud.web.socket;


public enum Action {
    MACHINE_NEW,
    MACHINE_UPDATED,
    MACHINE_DELETED,
    MACHINE_CONNECTED,
    MACHINE_DISCONNECTED,
    SEGMENT_UPLOADED,
    SEGMENT_DELETED,
    FILE_UPLOADED,
    FILE_DELETED,
    BALANCE_SEGMENTS_MOVED
}
