package mnix.mobilecloud.web.socket;


public enum Action {
    MACHINE_NEW,
    MACHINE_UPDATED,
    MACHINE_DELETED,
    MACHINE_CONNECTED,
    MACHINE_DISCONNECTED,
    SEGMENT_UPLOAD_START,
    SEGMENT_UPLOAD_END,
    SEGMENT_DELETED,
    FILE_UPLOAD_START,
    FILE_UPLOAD_END,
    FILE_DELETED
}
